### ISSUE TITLE
git install fails

### ISSUE THREAD

**Issue by davidhalter** [jyio/botbrew-gui#21]
The following error occurs: 

```
# apt-get install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
git : Depends: git-man (> 1:1.7.10.4) but 1:1.7.10-1em1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I don't think this is a problem of your software, looks more like a debian problem. But do you have any ideas?

**Comment by jyio** [comment]
We're probably in the process of getting an updated _git_, so we'll have to wait for the new _git-man_. If you want to install it right now but don't need to access the manual using `man` or `git help`, I had a crack at removing the dependency: http://dl.dropbox.com/u/1213413/git_1.7.10.4-1em1_armel.deb (it installs for me using either the command line or the GUI).

**Comment by davidhalter** [comment]
This works. Probably just a little embedded debian problem.
